name: Prod - Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Install Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 🔨 Build Project
        run: |
          yarn
          yarn build-prod

      - name: 📂 Deploy to Server
        uses: easingthemes/ssh-deploy@v4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          # ARGS: "-rltgoDzvO --delete"
          SOURCE: 'dist/'
          REMOTE_HOST: 82.29.156.38
          REMOTE_USER: u106957989
          REMOTE_PORT: '65002'
          TARGET: domains/codedthemes.com/public_html/demos/admin-templates/datta-able/angular/free
          EXCLUDE: '/node_modules/'
